# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(1012, 743)
        self.verticalLayout = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.frame_4 = QtGui.QFrame(Dialog)
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 311))
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.frame_4)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.frame_2 = QtGui.QFrame(self.frame_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label = QtGui.QLabel(self.frame_2)
        self.label.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_2.addWidget(self.label)
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_3 = QtGui.QLabel(self.frame_2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_3)
        self.N_Chrom = QtGui.QSpinBox(self.frame_2)
        self.N_Chrom.setMaximum(9999999)
        self.N_Chrom.setObjectName(_fromUtf8("N_Chrom"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.N_Chrom)
        self.label_5 = QtGui.QLabel(self.frame_2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_5)
        self.Chrm_is_F = QtGui.QCheckBox(self.frame_2)
        self.Chrm_is_F.setText(_fromUtf8(""))
        self.Chrm_is_F.setObjectName(_fromUtf8("Chrm_is_F"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.Chrm_is_F)
        self.label_6 = QtGui.QLabel(self.frame_2)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_6)
        self.Chrm_min = QtGui.QLineEdit(self.frame_2)
        self.Chrm_min.setObjectName(_fromUtf8("Chrm_min"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.Chrm_min)
        self.label_7 = QtGui.QLabel(self.frame_2)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_7)
        self.Chrm_max = QtGui.QLineEdit(self.frame_2)
        self.Chrm_max.setObjectName(_fromUtf8("Chrm_max"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.Chrm_max)
        self.verticalLayout_2.addLayout(self.formLayout_2)
        self.horizontalLayout_2.addWidget(self.frame_2)
        self.frame = QtGui.QFrame(self.frame_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_2 = QtGui.QLabel(self.frame)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_3.addWidget(self.label_2)
        self.formLayout_3 = QtGui.QFormLayout()
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.label_4 = QtGui.QLabel(self.frame)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_4)
        self.Size_of_pool = QtGui.QSpinBox(self.frame)
        self.Size_of_pool.setMinimum(100)
        self.Size_of_pool.setMaximum(9999)
        self.Size_of_pool.setProperty("value", 1000)
        self.Size_of_pool.setObjectName(_fromUtf8("Size_of_pool"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.Size_of_pool)
        self.label_8 = QtGui.QLabel(self.frame)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_8)
        self.Child_mode = QtGui.QComboBox(self.frame)
        self.Child_mode.setObjectName(_fromUtf8("Child_mode"))
        self.Child_mode.addItem(_fromUtf8(""))
        self.Child_mode.addItem(_fromUtf8(""))
        self.Child_mode.addItem(_fromUtf8(""))
        self.Child_mode.addItem(_fromUtf8(""))
        self.Child_mode.addItem(_fromUtf8(""))
        self.Child_mode.addItem(_fromUtf8(""))
        self.Child_mode.addItem(_fromUtf8(""))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.Child_mode)
        self.label_9 = QtGui.QLabel(self.frame)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_9)
        self.Selection_mode = QtGui.QComboBox(self.frame)
        self.Selection_mode.setObjectName(_fromUtf8("Selection_mode"))
        self.Selection_mode.addItem(_fromUtf8(""))
        self.Selection_mode.addItem(_fromUtf8(""))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.FieldRole, self.Selection_mode)
        self.label_10 = QtGui.QLabel(self.frame)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_10)
        self.Itmax = QtGui.QSpinBox(self.frame)
        self.Itmax.setObjectName(_fromUtf8("Itmax"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.FieldRole, self.Itmax)
        self.label_11 = QtGui.QLabel(self.frame)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.formLayout_3.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_11)
        self.High_Low = QtGui.QCheckBox(self.frame)
        self.High_Low.setText(_fromUtf8(""))
        self.High_Low.setObjectName(_fromUtf8("High_Low"))
        self.formLayout_3.setWidget(4, QtGui.QFormLayout.FieldRole, self.High_Low)
        self.label_14 = QtGui.QLabel(self.frame)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.formLayout_3.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_14)
        self.Chrm_can_repetead = QtGui.QCheckBox(self.frame)
        self.Chrm_can_repetead.setText(_fromUtf8(""))
        self.Chrm_can_repetead.setObjectName(_fromUtf8("Chrm_can_repetead"))
        self.formLayout_3.setWidget(5, QtGui.QFormLayout.FieldRole, self.Chrm_can_repetead)
        self.label_12 = QtGui.QLabel(self.frame)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.formLayout_3.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_12)
        self.Elitism = QtGui.QSpinBox(self.frame)
        self.Elitism.setObjectName(_fromUtf8("Elitism"))
        self.formLayout_3.setWidget(6, QtGui.QFormLayout.FieldRole, self.Elitism)
        self.label_13 = QtGui.QLabel(self.frame)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.formLayout_3.setWidget(7, QtGui.QFormLayout.LabelRole, self.label_13)
        self.Mute = QtGui.QSpinBox(self.frame)
        self.Mute.setObjectName(_fromUtf8("Mute"))
        self.formLayout_3.setWidget(7, QtGui.QFormLayout.FieldRole, self.Mute)
        self.verticalLayout_3.addLayout(self.formLayout_3)
        self.horizontalLayout_2.addWidget(self.frame)
        self.frame_2.raise_()
        self.frame.raise_()
        self.verticalLayout.addWidget(self.frame_4)
        self.frame_3 = QtGui.QFrame(Dialog)
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.frame_3)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_15 = QtGui.QLabel(self.frame_3)
        self.label_15.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.verticalLayout_4.addWidget(self.label_15)
        self.Funt_Fitness = QtGui.QPlainTextEdit(self.frame_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Funt_Fitness.sizePolicy().hasHeightForWidth())
        self.Funt_Fitness.setSizePolicy(sizePolicy)
        self.Funt_Fitness.setMinimumSize(QtCore.QSize(0, 300))
        self.Funt_Fitness.setObjectName(_fromUtf8("Funt_Fitness"))
        self.verticalLayout_4.addWidget(self.Funt_Fitness)
        self.verticalLayout.addWidget(self.frame_3)
        self.Aceptar_Cancelar = QtGui.QDialogButtonBox(Dialog)
        self.Aceptar_Cancelar.setOrientation(QtCore.Qt.Horizontal)
        self.Aceptar_Cancelar.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.Aceptar_Cancelar.setObjectName(_fromUtf8("Aceptar_Cancelar"))
        self.verticalLayout.addWidget(self.Aceptar_Cancelar)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.label.setText(_translate("Dialog", "Chromosome params", None))
        self.label_3.setText(_translate("Dialog", "Number of Chromosomes", None))
        self.label_5.setText(_translate("Dialog", "Value of Chromosome is float", None))
        self.label_6.setText(_translate("Dialog", "Minimum value", None))
        self.Chrm_min.setText(_translate("Dialog", "0", None))
        self.label_7.setText(_translate("Dialog", "Maximum value", None))
        self.Chrm_max.setText(_translate("Dialog", "0", None))
        self.label_2.setText(_translate("Dialog", "Parameters of Genetic Algorithm", None))
        self.label_4.setText(_translate("Dialog", "Size of pool", None))
        self.label_8.setText(_translate("Dialog", "Child mode", None))
        self.Child_mode.setItemText(0, _translate("Dialog", "CHILD FLIP", None))
        self.Child_mode.setItemText(1, _translate("Dialog", "CHILD_SPLIT", None))
        self.Child_mode.setItemText(2, _translate("Dialog", "CHILD_FLIP_TOURNAMENT_DETERMINISTIC", None))
        self.Child_mode.setItemText(3, _translate("Dialog", "CHILD_FLIP_TOURNAMENT_PROBABILISTIC", None))
        self.Child_mode.setItemText(4, _translate("Dialog", "CHILD_MEAN", None))
        self.Child_mode.setItemText(5, _translate("Dialog", "CHILD_SPLIT_TOURNAMENT_DETERMINISTIC", None))
        self.Child_mode.setItemText(6, _translate("Dialog", "CHILD_SPLIT_TOURNAMENT_PROBABILISTIC", None))
        self.label_9.setText(_translate("Dialog", "Selection mode", None))
        self.Selection_mode.setItemText(0, _translate("Dialog", "FILL", None))
        self.Selection_mode.setItemText(1, _translate("Dialog", "ROULETE", None))
        self.label_10.setText(_translate("Dialog", "It max", None))
        self.label_11.setText(_translate("Dialog", "Sort High to Low", None))
        self.label_14.setText(_translate("Dialog", "Chromosomes can be repeated", None))
        self.label_12.setText(_translate("Dialog", "Elitism", None))
        self.label_13.setText(_translate("Dialog", "Probability of mutating", None))
        self.label_15.setText(_translate("Dialog", "Function Fitness", None))
        self.Funt_Fitness.setPlainText(_translate("Dialog", "#Variables to calculate fitness\n"
"def Fitness(item):\n"
"    \"\"\"\n"
"    item is of type array of crhomosomes\n"
"    Your code for calculate fitnness\n"
"    \"\"\"\n"
"    return fitness", None))

